packages:
  - "packages/**"
  - "examples/**"
  - "frameworks/**"
  - "test/**"
  - "docs/**"
  - 'talks/**'
  - "!**/.tmp/**"
options:
  prefer-workspace-packages: true
  strict-peer-dependencies: false
